### ISSUE TITLE
Cannot verify signature

### ISSUE THREAD

**Issue by eimantaaas** [ohdearapp/laravel-ohdear-webhooks#11]
Hi, I'm using webhook signing secret provided in Webhook notifications configuration tab, but as I debug with Laravel Telescope package says that signature is invalid. Any suggestions what can be wrong?

I have double checked signing secret in .env file and it is equal with signing secret in oh dear app.

`{
"error": "The signature 'xxxxxxxxx' found in the header named 'OhDear-Signature' is invalid. Make sure that the 'ohdear-webhooks.signing_secret' config key is set to the value you found on the OhDear dashboard. If you are caching your config try running 'php artisan clear:cache' to resolve the problem."
}`

**Comment by freekmurze** [comment]
That's strange.

You can debug it by seeing if the payload is what you'd expect to come in, by adding a dump statement here: https://github.com/ohdearapp/laravel-ohdear-webhooks/blob/master/src/OhDearWebhooksController.php#L19

Also take a look if the `hash_hmac` function gets the parameters you'd expect.
https://github.com/ohdearapp/laravel-ohdear-webhooks/blob/master/src/Middlewares/VerifySignature.php#L33

**Comment by eimantaaas** [comment]
Yes, I tried to debug at this point:
https://github.com/ohdearapp/laravel-ohdear-webhooks/blob/master/src/Middlewares/VerifySignature.php#L33

so I see that `$payload` and `$secret` is set and looks fine, but `hash_hmac` generates different signature comparing with one provided in Oh Dear webhook headers.

**Comment by freekmurze** [comment]
Could you send an email to support@ohdear.app mentioning your team name, the secret you are using and a few screenshots of your debugging efforts? We'll take it from there.
