### ISSUE TITLE
Wrong command mentioned in WebhookFailed. 

### ISSUE THREAD

**Issue by santal1981** [ohdearapp/laravel-ohdear-webhooks#12]
Minor issue, please change clear:config to config:clear. 

Cheers

https://github.com/ohdearapp/laravel-ohdear-webhooks/blob/0f5e5b37b0ece844b0fc0be8bfc78397c92ef664/src/Exceptions/WebhookFailed.php#L17

**Comment by freekmurze** [comment]
This has been fixed 👍
