### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by arwinvdv** [ohdearapp/laravel-ohdear-webhooks#15]
Hi!

Is it true that the documentation to setup this package is gone? 
When I look at this page https://ohdear.app/docs/integrations/webhooks it says nothing about it, and this page https://ohdear.app/docs/integrations/the-oh-dear-php-sdk doesn't seem to say anything either.

**Comment by freekmurze** [comment]
It seems like we removed the documentation of this package by accident when we did our redesign last year.

I'll add it back soon!

**Comment by freekmurze** [comment]
I've updated the readme of this package with full instructions 👍
