### ISSUE TITLE
https://ohdearapp.com/xxxxxx

### ISSUE THREAD

**Issue by ostark** [ohdearapp/laravel-ohdear-webhooks#4]
Oh Dear! @mattiasgeniar & @freekmurze 

I found this dummy link (https://ohdearapp.com/xxxxxx) in various places:

* https://ohdearapp.com/docs/webhooks/laravel-package
* https://github.com/ohdearapp/laravel-ohdear-webhooks/blob/master/config/ohdear-webhooks.php
* https://github.com/spatie/dashboard.spatie.be/blob/master/config/ohdear-webhooks.php

It should be https://ohdearapp.com/team-settings/notifications (plus anchor would be nice)

Cheers
Oli

**Comment by freekmurze** [comment]
Hi Oli, thanks for bringing this to my attention. 👍 

I've fixed the links. If you spot some other problems or have some questions about the service, do let us know!
